networks:
  shared:

services:
  postgres:
    image: pgvector/pgvector:pg15
    networks:
      - shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - shared
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
